name: Build and Publish Wheels
on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade packaging requests scikit-build-core nanobind build ninja cibuildwheel auditwheel

    - name: Fetch TDLib version and commit hash
      id: vars
      run: |
        LATEST_TDLIB_COMMIT_HASH=$(curl -s "https://api.github.com/repos/tdlib/td/commits/master" | grep -oP '"sha": "\K[^"]+' | head -1)
        LATEST_TDLIB_VERSION=$(curl -s "https://raw.githubusercontent.com/tdlib/td/$LATEST_TDLIB_COMMIT_HASH/CMakeLists.txt" | grep -oP 'project\(TDLib VERSION \K[0-9\.]+')

        echo "LATEST_TDLIB_COMMIT_HASH=$LATEST_TDLIB_COMMIT_HASH" >> $GITHUB_OUTPUT
        echo "LATEST_TDLIB_VERSION=$LATEST_TDLIB_VERSION" >> $GITHUB_OUTPUT
        echo "PYPI_RELEASE_VERSION=$(python next_version.py $LATEST_TDLIB_VERSION)" >> $GITHUB_OUTPUT

    - name: Update pyproject.toml and README.md with latest TDLib version
      run: |
        LATEST_TDLIB_VERSION=${{ steps.vars.outputs.LATEST_TDLIB_VERSION }}
        PYPI_RELEASE_VERSION=${{ steps.vars.outputs.PYPI_RELEASE_VERSION }}

        sed -i -r "s/^version = \".*\"/version = \"$PYPI_RELEASE_VERSION\"/" pyproject.toml
        sed -i -r "s/^__version__ = \".*\"/__version__ = \"$PYPI_RELEASE_VERSION\"/" tdjson/__init__.py

        sed -i -r "s|(https://img.shields.io/badge/TDLib-v)[0-9\.]+(-blue)|\\1$LATEST_TDLIB_VERSION\\2|" README.md

    - name: Commit updated files
      uses: EndBug/add-and-commit@v9
      with:
        message: "Update TDLib to ${{ steps.vars.outputs.LATEST_TDLIB_VERSION }} (tdlib/td@${{ steps.vars.outputs.LATEST_TDLIB_COMMIT_HASH }})"
        add: '["pyproject.toml", "README.md", "tdjson/__init__.py"]'
        committer_name: GitHub Actions
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com

    - name: Build wheels
      run: |
        mkdir -p dist
        python -m cibuildwheel .
        mv ./wheelhouse/*.whl dist/
        ls dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
